### ISSUE TITLE
Crash on delete recording 

### ISSUE THREAD

**Issue by AMMARLAFIR** [Leonidius20/RecordingStudio#10]
Build version: 0.1.3 
Current date: 2024-09-27 11:33:53 
Device: Samsung SM-A155F 
OS version: Android 14 (SDK 34) 
 
Stack trace:  
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1510126372, result=-1, data=null} to activity {io.github.leonidius20.recorder.lite/io.github.leonidius20.recorder.MainActivity}: java.lang.NullPointerException
	at android.app.ActivityThread.deliverResults(ActivityThread.java:6063)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:6102)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
Caused by: java.lang.NullPointerException
	at O2.n.a(SourceFile:38)
	at e.h.a(SourceFile:45)
	at c.m.onActivityResult(SourceFile:3)
	at e0.C.onActivityResult(SourceFile:6)
	at android.app.Activity.dispatchActivityResult(Activity.java:9362)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:6056)
	... 13 more

**Comment by Leonidius20** [comment]
Hello and thank you for reporting this issue.
It will be fixed in the next version, i will comment here once it becomes available

**Comment by maroeldawwyp** [comment]
> Build version: 0.1.3 Current date: 2024-09-27 11:33:53 Device: Samsung SM-A155F OS version: Android 14 (SDK 34)
> 
> Stack trace: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1510126372, result=-1, data=null} to activity {io.github.leonidius20.recorder.lite/io.github.leonidius20.recorder.MainActivity}: java.lang.NullPointerException at android.app.ActivityThread.deliverResults(ActivityThread.java:6063) at android.app.ActivityThread.handleSendResult(ActivityThread.java:6102) at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67) at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45) at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139) at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685) at android.os.Handler.dispatchMessage(Handler.java:106) at android.os.Looper.loopOnce(Looper.java:230) at android.os.Looper.loop(Looper.java:319) at android.app.ActivityThread.main(ActivityThread.java:8919) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) Caused by: java.lang.NullPointerException at O2.n.a(SourceFile:38) at e.h.a(SourceFile:45) at c.m.onActivityResult(SourceFile:3) at e0.C.onActivityResult(SourceFile:6) at android.app.Activity.dispatchActivityResult(Activity.java:9362) at android.app.ActivityThread.deliverResults(ActivityThread.java:6056) ... 13 more

Confirmed

**Comment by Leonidius20** [comment]
Version 0.1.4 has just been released and it should fix the issue. It is now available in the Releases section. Please check.
