### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by flitzfa** [Leonidius20/RecordingStudio#14]
Build version: 0.1.3 
Current date: 2024-10-04 14:05:47 
Device: Xiaomi Redmi Note 4 
OS version: Android 10 (SDK 29) 
 
Stack trace:  
java.lang.RuntimeException: Unable to start activity ComponentInfo{io.github.leonidius20.recorder.lite/io.github.leonidius20.recorder.MainActivity}: java.lang.UnsupportedOperationException: Unknown windowLayoutInDisplayCutoutMode: 3
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3271)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3410)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2017)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7396)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
Caused by: java.lang.UnsupportedOperationException: Unknown windowLayoutInDisplayCutoutMode: 3
	at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:2503)
	at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2705)
	at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2095)
	at io.github.leonidius20.recorder.MainActivity.onCreate(SourceFile:28)
	at android.app.Activity.performCreate(Activity.java:7824)
	at android.app.Activity.performCreate(Activity.java:7813)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1323)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3246)
	... 11 more

**Comment by Leonidius20** [comment]
Version 0.1.4 has just been released and it should fix the crash. It is now available in the Releases section.
