### ISSUE TITLE
App crashes when attempting to record into ogg vorbis

### ISSUE THREAD

**Issue by pvagner** [Leonidius20/RecordingStudio#2]
### Steps

* Open the app
* Expand the recording setup
* Leave everything at the default and change Container format to OGG and Codec to Vorbis.
* Dismiss the recording setup
* Hit Record / Pause button

### Actual

The app crashes

### Expected

Recording into ogg vorbis should be possible.

### Crash and device data

Build version: 0.1.0 
Current date: 2024-09-08 19:22:33 
Device: Samsung SM-A546B 
OS version: Android 14 (SDK 34) 
 
Stack trace:  
java.lang.RuntimeException: Unable to start service io.github.leonidius20.recorder.data.recorder.RecorderService@6684ec4 with Intent { cmp=io.github.leonidius20.recorder.lite/io.github.leonidius20.recorder.data.recorder.RecorderService }: java.lang.RuntimeException: start failed.
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5286)
	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2531)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8893)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
Caused by: java.lang.RuntimeException: start failed.
	at android.media.MediaRecorder._start(Native Method)
	at android.media.MediaRecorder.start(MediaRecorder.java:1591)
	at io.github.leonidius20.recorder.data.recorder.RecorderService.onStartCommand(SourceFile:431)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5268)
	... 9 more

**Comment by Leonidius20** [comment]
Hello and thank you for reporting this issue!
as it turned out during my investigation, Android does not support encoding Vorbis, at least without any 3rd party libraries. I will remove this option in a future version.

**Comment by pvagner** [comment]
Thanks for investigating and explaining this. I understand.
