### ISSUE TITLE
App instantly crashes on recording (directory not allowed)

### ISSUE THREAD

**Issue by AnatolyIliev** [Leonidius20/RecordingStudio#7]
Build version: 0.1.1 
Current date: 2024-09-09 17:07:50 
Device: Motorola moto g 5G 
OS version: Android 11 (SDK 30) (LineageOS 18.1)
 
Stack trace:  
java.lang.RuntimeException: Unable to start service io.github.leonidius20.recorder.data.recorder.RecorderService@be914e5 with Intent { cmp=io.github.leonidius20.recorder.lite/io.github.leonidius20.recorder.data.recorder.RecorderService }: java.lang.IllegalArgumentException: Primary directory Recordings not allowed for content://media/external/audio/media; allowed directories are [Alarms, Audiobooks, Music, Notifications, Podcasts, Ringtones]
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4338)
	at android.app.ActivityThread.access$1800(ActivityThread.java:237)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1951)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.IllegalArgumentException: Primary directory Recordings not allowed for content://media/external/audio/media; allowed directories are [Alarms, Audiobooks, Music, Notifications, Podcasts, Ringtones]
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
	at android.content.ContentProviderProxy.insert(ContentProviderNative.java:549)
	at android.content.ContentResolver.insert(ContentResolver.java:2149)
	at android.content.ContentResolver.insert(ContentResolver.java:2111)
	at io.github.leonidius20.recorder.data.recorder.RecorderService.onStartCommand(SourceFile:320)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4320)
	... 8 more

**Comment by Leonidius20** [comment]
Thank you for reporting this issue!
It will be fixed in a future version.
I will keep the issue open until this new version releases.

**Comment by AnatolyIliev** [comment]
Recording is fixed! However - the list of recordings doesn't work, and the playback buttons are blacking out.

https://github.com/user-attachments/assets/b6bed3f5-9acf-40dd-9f90-a4ecd752ea56

**Comment by Leonidius20** [comment]
Should be fixed in the next version, i will leave a comment here when it becomes available

**Comment by Leonidius20** [comment]
Version 0.1.3 now available in the Releases section. Please check if it solved the issue

**Comment by AnatolyIliev** [comment]
> Version 0.1.3 now available in the Releases section. Please check if it solved the issue

Yep! Now I just hope the audio quality gets fixed, because opus is reeeeeeeally crusty #3.

This is the only FOSS recording app *with* a sane UI which works on my phone - all the rest seem to either be forks of some underlying codebase which constantly crashes and takes 10 seconds to load, and/or they have a dogshit interface. Thank you!

**Comment by Leonidius20** [comment]
@AnatolyIliev Hey there!
I wanted to let you know that the newest version (0.2.0) supports setting sample rate and bit rate for OPUS. With the right settings the quality should be fine.
